name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-eng poppler-utils
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn python-multipart pdf2image pytesseract Pillow
        pip install pytest httpx
    
    - name: Run tests
      run: |
        pytest test_main_simplified.py -v

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort
    
    - name: Check if files exist
      run: |
        ls -la
        echo "main.py exists:" && test -f main.py && echo "YES" || echo "NO"
    
    - name: Run black (if main.py exists)
      run: |
        if [ -f main.py ]; then
          black --check main.py
        else
          echo "main.py not found, skipping black check"
        fi
    
    - name: Run flake8 (if main.py exists) 
      run: |
        if [ -f main.py ]; then
          flake8 main.py --max-line-length=88 --extend-ignore=E203,E501,W503
        else
          echo "main.py not found, skipping flake8 check"
        fi
        
    - name: Run isort (if main.py exists)
      run: |
        if [ -f main.py ]; then
          isort --check-only main.py
        else
          echo "main.py not found, skipping isort check"
        fi